// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmnwirbvbhsiettklzne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbndpcmJ2YmhzaWV0dGtsem5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjMyMzYsImV4cCI6MjA2OTk5OTIzNn0.PQCyv4uuvz5g7lwJxkc1VoUZwzWxKBj1ysJn5cIlm2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});